### ISSUE TITLE
when adding child or parent all .org files are loaded into emacs, why?

### ISSUE THREAD

**Issue by michaelsjackson** [Kungsgeten/org-brain#117]
I have lots of .org files in the org-brain path, when I try to add a new parent or child to the brain, org-brain loads|opens all .org files in the org-brain path, this takes lots of time. Is this step really necessary or can we prevent it by setting any variable?  How many .org files do I have? 2433.

**Comment by michaelsjackson** [comment]
Yes, it takes a lot of time and this is for me a showstopper, then I am just opening .org files from dired, instead of opening from org-brain, plus letting go of concept mapping inside org-brain. One alternative way could be as follows:

1.  Not suggesting any entries, thus nothing has to be scanned nor any list generated.

2.  org-brain should only check if a file with this name exists, not checking any file content.

3.  wiki pages might have a similar feature, like keeping all network structure in a separate file, updating permanently this file only. each entry would be a line in this, tab separated entries to other entries, parents defined as p::_____, children defined as c::_____, friends as f::_____. Here one such line:

brain    c::org-brain    p::network    p::concept_mapping    f::thought

This file could be alphabetically sorted, line by line.  I guess oddmuse wiki used a similar concept.

**Comment by Kungsgeten** [comment]
Some kind of entry caching might be a good idea. It would be a pretty big update to do something like that, but it is probably doable.

**Comment by Whil-** [comment]
I'm experiencing this slowness as well. My operating system is windows though, and nowhere nere the 2k number of files. For solving this my thought goes to caching as well. A cache to store all the ID's, titles and filenames that would be an optional way (or mandatory?) way of letting org-brain work with all relations. The trick would be to provide functions that can maintain the integrity of the cache. Full integrity is ofc impossible, as the org-brain-links can be modified manually. So some kind of "update cache" function would be needed. As well as additions in/advices to the existing add/remove-child/parent/friend functions :)

My 2 cents anyways!

**Comment by Kungsgeten** [comment]
I'm currently working on #118 and trying out having a cache for files. If that turns out well, I think it might be possible to have a cache for all entries and their relationships.

**Comment by baygeldin** [comment]
@Kungsgeten, a relatively easy way to improve performance is to keep a list of files in `org-brain` directory with their `Last Modified` timestamps and invalidate cache only for those files which timestamps have changed since the last startup.

**Comment by Kungsgeten** [comment]
An update has been made to the way `org-brain` scans files. It no longer opens the files, but instead pastes their content into a temporary buffer. Please try and see if you notice any improvements.

**Comment by Kungsgeten** [comment]
Since files are no longer loaded, I'm marking this as closed.

**Comment by namdnguyen** [comment]
Org-brain is still opening all files when I add a relationship. Is the caching still being used? If so, do I need to do something to update the cache to prevent all files being opened?

**Comment by michaelsjackson** [comment]
Would using sqlite database together with org-brain make any sense? Of course it should happen all in the background, automatically. Just one more idea.

**Comment by Kungsgeten** [comment]
Now all files get opened again because I'm using `org-ql` to scan through files. At the moment there's nothing to do to prevent this. Using sqlite or similar could help, but I like the concept of it all being plain text.

**Comment by Kungsgeten** [comment]
See #251

**Comment by namdnguyen** [comment]
Ah, I see. Yes, I see a performance hit. I"m working with 500 notes, so it's pretty slow (several minutes) the first time trying to add a relationship because all the files are opening. After that, it's about 5-6 seconds for me to get the list of targets.

Org-ql seems like an expensive operation to perform without caching the results because we're not filtering on any of the results. For `org-brain-goto` related functions, those would filter by the note ID and BRAIN relationship lists of IDs. These are still fairly simple org-ql queries that could benefit from caching. 

Essentially, it would be beneficial to define which elements or properties can serve as an "index column", like how you would have in a database to speed up queries.

`org-roam` has a [caching layer](https://github.com/jethrokuan/org-roam/blob/develop/org-roam.el#L166), which only stores the headlines, forward links, and backward links. It's updated asynchronously.

`org-zettelkasten` uses a more advanced [caching layer](https://github.com/l3kn/org-el-cache), which looks like it persists all elements parsable by org-element. Has shell command dependencies (find, xargs, sha1sum) to determine when updates have been made to files 

`org-sql` provides a [SQLite backend](https://github.com/ndwarshuis/org-sql), but it adds SQLite as a dependency and would be more of a replacement for org-ql + something like org-el-cache.

**Comment by namdnguyen** [comment]
Does `org-brain` provide functionality to the user that wrap around `org-ql` for more advanced querying or is it an internal package for core org-brain functionality, like for finding all relationships for a note? In other words, are the queries being passed to org-ql of the same type and predictable?

**Comment by michaelsjackson** [comment]
You could use an older version of org-brain, where all files were not opened, I guess.

**Comment by namdnguyen** [comment]
Thanks for the suggestion, @michaelsjackson. I have thought about that workaround. It hasn't become unusable, yet, so I've been ok with the delays. I currently confine my org-brain work to a persp layer and then kill it when I'm done, so that it kills all the associated buffers with that persp.

**Comment by Kungsgeten** [comment]
@namdnguyen The latest commit removes the `org-ql` dependency. I've implemented a simple cache and to me it seems pretty fast so far. Files are no longer opened by `org-brain` when cached.

**Comment by namdnguyen** [comment]
Hi @Kungsgeten, just checking back in. I had a chance to try out adding note relationships today and your changes have made it significantly faster! Practically instantaneous once the cache is built. Thank you for the update!
