### ISSUE TITLE
opml export, starting from current entry, up to a given distance

### ISSUE THREAD

**Issue by michaelsjackson** [Kungsgeten/org-brain#148]
Same concept as before for org-mind-map-write, but now as opml export. It's advantage would be, you could import this opml into freeplane and make it more beautiful visually, for presentations for example. In short it would allow making reuse of your collections or notes inside org-brain, elsewhere, thanks to opml format.

**Comment by Kungsgeten** [comment]
Man people have suggested some sort of export feature. It is probably doable, if the exported format supports what org-brain does (multiple parents/children and maybe also the friends concept).

**Comment by Kungsgeten** [comment]
If anyone could provide some guidance for a visualization tool which supports the different kind of relations thats possible in `org-brain`, please let me know. Most mind mapping software for instance seem to only allow one parent, and one root. I'm think that GraphViz could work, but when I tried it I couldn't get it to look the way I wanted.

**Comment by techapu** [comment]
Hi! I'm also interested in an export feature! It is not so easy, by the way, to adapt a format to a data representation like the one org-brain manages. I think (I'm not an opml expert by the way...) that it is difficult to represent multiple parents or such relationships in that format.
I think one more easy (not so easy) approach to export like @michaelsjackson proposed originally would be the wiki approach. Non dinamic, an exporter that "shows" the info saved in org-brain. An exporter code that could generate like an sofisticated html that shows data as one can see in the org-brain buffer. Similar to a wikipedia page. One thought with some content visualized, and next to the title, the links to the multiple parents. After that, the content. Down, like a footnote, the "see also" reference: the links to the multiple friends, and the childs. I don't know how to represent the siblings. It's not so easy, but the software that inspired this one, "thebrain.com", has a visualizer (I think it is in Java) to show the real connections Maybe it is because other way is difficult. 
And also thebrain has a ".brain" extension that is based on XML. It can export to json, xml, text outlines, html. But it loses some relationship and attachs in the road.
The optimal approach would be to export in such a way that allows to continue working with the data and relationships and contents with other tools outside org-brain, or even outside Emacs. I wonder if the real perspective of this kind of knowledge representation wouldn't be a graph database format.

![graph-format-table-comparison](https://user-images.githubusercontent.com/34004712/58948640-f34c8800-8760-11e9-835e-9e04a974a993.png)

**Comment by Kungsgeten** [comment]
@techapu @michaelsjackson I've started a new repository named [org-brain-export](https://github.com/Kungsgeten/org-brain-export). I think discussions focused on exporting could be moved there. A starting point could be: https://github.com/Kungsgeten/org-brain-export/issues/2

I'm closing this since I think exporting discussions could take place there.
