### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by analyticd** [Kungsgeten/org-brain#16]
Thank you for your work on this project. I am hopeful that we can improve its
performance. I am retrofitting, so to speak, my collection of org files into the
org-brain way of doing things. Running org-brain-visualize on a small file with
only 3 subtrees, each small, takes quite a long time. [Aside: I have
approximately 700 org files in my org directory.] I ran M-x elp-instrument-package RET org-brain and then M-x elp-results and discovered the following

 | Function name                     | Call Count | Elapsed Time | Average Time |
|---|---|---|---|
 | org-brain-visualize               |          1 |      33.7054 |      33.7054 |
 | org-brain-parents                 |          1 |     18.14708 |     18.14708 |
 | org-brain-keywords                |        397 | 15.416008000 | 0.0388312544 |
 | org-brain-pins                    |          1 |    14.345758 |    14.345758 |
 | org-brain-title                   |         25 | 1.1664720000 | 0.0466588800 |
 | org-brain-insert-visualize-button |         12 | 0.5735349999 | 0.0477945833 |
 | org-brain-files                   |          3 | 0.2527109999 | 0.0842369999 |
 | org-brain-path-entry-name         |       1116 | 0.0291099999 | 2.608...e-05 |
 | org-brain-entry-path              |        401 | 0.0151009999 | 3.765...e-05 |
 | org-brain-resources               |          1 |     0.014433 |     0.014433 |
 | org-brain-children                |          1 |     0.010491 |     0.010491 |
 | org-brain-visualize-mode          |          1 |      0.00368 |      0.00368 |
 | org-brain-insert-resource-button  |          2 |     0.000214 |     0.000107 |

which shows, I think, that org-brain-parents, org-brain-children, and org-brain-pins are the
bottlenecks. 

I forked the project and implemented/committed caching for org-brain files, children, and parents resulting in a 2x speed up.  I'll try to get a pull request together soon, otherwise please just port the changes over. This update should help everyone, especially people with a large org file repo.

After the cache implementation, and a cache miss which initiates building of the cache, we have much better numbers

 | Function name                     | Call Count | Elapsed Time | Average Time |
|---|---|---|---|
| org-brain-visualize                  |   1       |   15.835363   | 15.835363|
| org-brain-keywords                   |   401     |   15.787954999| 0.0393714588|
| org-brain-pins                       |   1       |   14.634235   | 14.634235|
| org-brain-title                      |   27      |   1.1756829999| 0.0435438148|
| org-brain-insert-visualize-button    |   13      |   0.5837049999| 0.0449003846|
| org-brain-entry-path                 |   404     |   0.0253169999| 6.266...e-05|
| org-brain-files                      |   1       |   0.020009    | 0.020009|
| org-brain-path-entry-name            |   374     |   0.0194809999| 5.208...e-05|
| org-brain-resources                  |   1       |   0.01172     | 0.01172|
| org-brain-visualize-mode             |   1       |   0.001636    | 0.001636|
| org-brain-insert-resource-button     |   2       |   0.000133    | 6.65e-05|
| org-brain-children                   |   1       |   2e-06       | 2e-06|
| org-brain-parents                    |   1       |   1e-06       | 1e-06|
 
Now I've added the ability to pin through the org-brain-visualize interface,
bound to "P". Doing so allows consistent caching and validation of
org-brain-pins, which I have also now implemented. We now have an enormous
increase in speed:

 | Function name                     | Call Count | Elapsed Time | Average Time |
|---|---|---|---|
| org-brain-visualize                |     1     |     1.018994    | 1.018994|
| org-brain-title                    |     28    |     0.8870419999| 0.0316800714|
| org-brain-keywords                 |     28    |     0.8867950000| 0.0316712500|
| org-brain-insert-visualize-button  |     14    |     0.3781      | 0.0270071428|
| org-brain-resources                |     1     |     0.008334    | 0.008334|
| org-brain-entry-path               |     31    |     0.0016150000| 5.209...e-05|
| org-brain-visualize-mode           |     1     |     0.001558    | 0.001558|
| org-brain-insert-resource-button   |     2     |     4.9e-05     | 2.45e-05|
| org-brain-parents                  |     1     |     3e-06       | 3e-06|
| org-brain-children                 |     1     |     3e-06       | 3e-06|
| org-brain-pins                     |     1     |     2e-06       | 2e-06|
 
I think this is getting quite usable.

Cache invalidation happens at the correct times. If you make changes to pins or
brainchildren outside the org-brain-visualize interface, I've added M-x
org-brain-invalidate-all-caches. You shouldn't need to use that if you use the
org-brain-visualize interface/mode/keybindings though.

**Comment by Kungsgeten** [comment]
Hi!

It is indeed true that there is perfomance issues. The main problem is that each brain entry has to be scanned for children, in order to see if the visualized entry is linked to from any other file(s). The problem with caching (I would guess) is when to update the cache, making sure its in sync with the files?

I have two ideas for performance boosts:

1. Each file contain information about all of its parents. Now only the current file has to be parsed upon org-brain-visualize. The downside of this is keeping the child/parent-files in sync. If you remove a link from one file, it has to be removed someway in the other too. In order to do this I think we would need to write a function run during the save-hook in org-brain files. This idea is okay, but I think it is prone to errors. Another downside is that pinned entries will still take a lot of time, since we'll have to search all files in order to see which are pinned (could perhaps be cached or saved into an external file).

2. Have some sort of database. I've been looking into https://github.com/skeeto/emacsql and using emacsql-sqlite as a database. This would still need a function run in the save-hook, but would be easier (I think). The main downside is that things potentially could still get out of sync, but also an external dependency to another package, emacsql-sqlite compiles a separate binary for its database handling (which people may not like). Another database option is https://github.com/nicferrier/emacs-db which is done entirely in emacs-lisp, but seems a bit harder to use.

**Comment by analyticd** [comment]
Hi! Thanks for your response. I've implemented the caching and added pinning to the visualize interface. It is all now blazing fast with proper cache invalidation as far as my testing indicates. This is now really usable as a day to day solution. I am getting 1 second response times as indicated above.

**Comment by analyticd** [comment]
Yes, I've used emacsql before. I don't think it will be necessary now that the cache is in place. It is now plenty fast for me.
