### ISSUE TITLE
Question/advice: what to do if a resource fits multiple entries?

### ISSUE THREAD

**Issue by Trevoke** [Kungsgeten/org-brain#180]
I, relatively often, have resources that fit multiple entries. For instance:
- "how does AlphaGo work" fits both into "The game of go" and "machine learning"
- "chord progressions" fits into music theory and composition

I could put the resource in both entries, but I don't know if there's a better way to think about it. What are your suggestions?

**Comment by drbronner** [comment]
Not the maintainer, but in cases like this I often pull the shared resource into its own entry, and link it as a friend to both entries.

**Comment by Kungsgeten** [comment]
I don't really have a suggestion, I guess it depends on the case. Many times I think @drbronner is right, that the resource maybe should be in an entry of its own.

In your examples I would probably put "How does AlphaGo work" into "machine learning", since the technology behind it doesn't really seem relevant to the game of Go. If you on the other hand had an entry called "AlphaGo" which perhaps handles both the technology and its strategies, match records, etc, then I would put the resource there and make AlphaGo a friend.

Chord progressions I would probably create a new entry and maybe put it as a child to both music theory and composition.

On the other hand there's nothing saying that you can't simply just add the resources to both entries, even though its more elegant to avoid duplication.
