### ISSUE TITLE
Entry formatting for headline only

### ISSUE THREAD

**Issue by namdnguyen** [Kungsgeten/org-brain#233]
I only link to headlines, so I have configured org-brain to ignore file entries. My desired formatting for the entry selection list is to display the list of org-brain headline entries showing **only** the headline title.

Here are my entry formatting configuration:

```
org-brain-include-file-entries nil
org-brain-file-entries-use-title nil
org-brain-headline-entry-name-format-string "%s"
```

For this configuration, it will give me a list of headline entries, but show me the relative path file name of the file of the headline entry, instead of the desired headline entry title.

From what I gathered, `org-brain-entry-name` is the function that formats entries to display in the entry selection list. It retrieves and formats two objects: the file title and the headline title. 

Because I changed `org-brain-headline-entry-name-format-string` from the default `"%s::%s"` to `"%s"`, it's formatting the filename because that's the first object `org-brain-entry-name` gets.

Will the change for headline entry title only in the selection list need to be made in org-brain or to my `org-brain-headline-entry-name-format-string` value?

**Comment by Kungsgeten** [comment]
Hi! It may be a bit hard to find, and perhaps it should be mentioned somewhere so that it is easier to find (please tell me if you have any ideas). Anyway, if you read the documentation of `org-brain-headline-entry-name-format-string` you can see that it is sent to the emacs `format` function along with two objects: the file and the headline. You can then read the documentation of `format` to see how that function handles the format string and the objects.

To do what you want you can use the following config:

`(setq org-brain-headline-entry-name-format-string "%2$s")`

**Comment by namdnguyen** [comment]
Hi @Kungsgeten. Oh, man. I knew that there would be a way with `format`, and I did check the documentation for `format` but apparently I didn't read it well enough! Thank you so much for your quick reply to correct my configuration and for the awesome package!

**Comment by namdnguyen** [comment]
Oh, I forgot to answer your question. I think that it makes sense to add it in the README in the "Headline and file entries" section, which is what I consulted today to configure org-brain. I could take a stab at updating the README, if you'd like.

**Comment by Kungsgeten** [comment]
Sure, any help is appreciated!

Den tis 19 nov. 2019 07:18Nam D. Nguyen <notifications@github.com> skrev:
