### ISSUE TITLE
Does there exists a full text search for all org-brain files?

### ISSUE THREAD

**Issue by hokreb** [Kungsgeten/org-brain#245]
Does there exists a full text search for all org-brain files, which shows a kind of result page with link?
Or should this be done by help of other emacs packages (sorry, if this question is simple, but I am newbie emacs user)?

**Comment by Kungsgeten** [comment]
Hi! No, there's no such functionality in `org-brain`. Indeed it can be covered by other packages. One example is `helm-org-rifle` which you can read about in the `org-brain` README. Another nice option is [Deadgrep](https://github.com/Wilfred/deadgrep).

No worries regarding the question being simple! Its valid and it is a nice feature to have. I just feel like it isn't necessary to implement it directly in `org-brain`, because of the modularity in Emacs.

**Comment by shrysr** [comment]
I am inclined to agree this does not need to be implemented directly in org-brain. Other alternatives: ag from the [silver searcher library](https://github.com/ggreer/the_silver_searcher). I typically use ag / helm-ag or project-grep

**Comment by lionelyoung** [comment]
I use a combination of **deft** and **ag**

**Comment by Kungsgeten** [comment]
I'm closing this since I feel the question has been answered.
