### ISSUE TITLE
Add back link to the section in the file

### ISSUE THREAD

**Issue by riclage** [Kungsgeten/org-brain#248]
Following my usage of the awesome change done here: #241, I'm now faced with the following:

Say I add a link from a section in A to B. In B org-brain creates a link back to file A. But not in the section where the link was added. Can that be done?

For example, if I have a file A:
```
* My header

** My Subtitle 1

** My Subtitle 2
[[brain:304905-3432...][my link to brain file B]]
```

What I would expect in B is a link to `[[file:A.org::*My Subtitle 2]]`

**Comment by Kungsgeten** [comment]
Yes, that seems reasonable. I'm a bit busy with other projects at the moment, but I'll see what I can do.

**Comment by lionelyoung** [comment]
When I do org-insert-link, it's not creating backlinks.  How do I make this feature work?

I've done the following:

1. Set variable `(setq org-brain-backlink t)`
2. org-brain-visualize, then hit "l" to add a resource
3. Result: No link created here

I've also tried:
1. Set variable `(setq org-brain-backlink t)`
2. org-brain-visualize, then hit "o" to enter the .org file
3. Run `org-insert-link` then type: `brain:<somefile>`
4. Result: No backlink created here either, in either file, somefile or this

I'm on Emacs 26.3 with spacemacs

**Comment by riclage** [comment]
@Kungsgeten sorry to bother but do you have any update on this? Do you think I could try to make a PR for it? If yes, how do you propose I approach it? Thanks!

**Comment by Kungsgeten** [comment]
@riclage No I haven't looked into your issue. What @lionelyoung describes seems to be a bug (or usage error), but I haven't tried that either I'm afraid.

If you want to try a PR you're welcome! Its hard for me to help since I don't know your background in emacs-lisp, but I'll try :) Have a look at `org-brain-link-complete` and more specifically the code starting on line 3027. The `file` link is created there, and we'd need a check to see if we're under a headline, and if so which it is. Perhaps there's `org-mode` functionality for that, but I'm not sure.
