### ISSUE TITLE
adding child to an entry (in org-brain-visualize) via short-cut 'c'

### ISSUE THREAD

**Issue by hokreb** [Kungsgeten/org-brain#277]
I try to add an existing entry as a child in the org-brain-visualize mode (version 20200323.2040). The child entry is a headline entry (named new_entry) which exists already in a different file (_file.org). After I type in the entry at the prompt (new_entry), a new file with the name new_entry.org is created, and in the PROPERTIES at :BRAIN_CHILDREN: the name new_entry appears (and not the Id of the existing entry). It this an intended behaviour, or should there appear the existing ID of the existing headline entry (new_entry)?

**Comment by benjaminwd** [comment]
If the entry already exists in another file, you will need to put the file's org property name (the bit that comes after `#+TITLE:`) first, followed by `::` and then the entry. Otherwise it will default to creating a new file. For example, if I press `c` I then type `My Brain::new_entry`. You can also use tab for auto completion. I'm actually not sure what the behavior is if you are not using a title.

**Comment by hokreb** [comment]
Thanks for this hint, I was not aware of this!
