### ISSUE TITLE
Support alternative implementations of `completing-read`

### ISSUE THREAD

**Issue by egregius313** [Kungsgeten/org-brain#279]
While using `org-brain` many of the functions use `completing-read` to help select an entry. Often the way I memorize entries is by their name, not necessarily the full `file::entry` name. Alternative implementations of `completing-read` (such as those provided by ivy, helm, or even ido) would be nice.

This could be implemented similar to projectile, where users can customize a search system variable but it doesn't require the search systems it doesn't use.

**Comment by Kungsgeten** [comment]
Hi! I've seen your PR but haven't had the time to look at it yet. I will do so soon! Personally I have `ivy-mode` active, which then use `ivy-completing-read` instead of the default. There's also `ido-mode` and `helm-mode` available (and probably other commands like this for other completion packages).

The reason for providing customization of `org-brain` completion would be if a user wants to override their default completion system with something else?

**Comment by egregius313** [comment]
Yes, similar to how projectile does it.

For example, I use helm for a lot of functionality, but sometimes ivy or ido are nicer for something simpler/quicker depending on what you're doing

**Comment by Kungsgeten** [comment]
Fixed with #274 and #305
