### ISSUE TITLE
is it possible to brain link to headline entries?

### ISSUE THREAD

**Issue by xdrie** [Kungsgeten/org-brain#304]
currently, i am unable to insert a link to a headline entry (level 1 headline inside a brain file)

For example, with an entry `websites` in `websites.org` and a headline entry `github` created at `websites::github`:

`[[brain:websites::github][GitHub]]`

However, this link doesn't work, and emacs simply hangs for a few seconds then does nothing. Am I doing this wrong?

Thanks!!

**Comment by Kungsgeten** [comment]
Hi! The link part (after `brain:`) needs to refer to the ID of the entry. Files have the filename (relative to the `org-brain-path`) as their ID, but headline entries use `org-id` and have generated IDs like `c0437d1b-6f8a-429a-9fc5-9b32f66b9508`. Because of this it isn't practical to write these links by hand.

What I recommend instead is to use `org-insert-link` to insert a link. It is bound to `C-c C-l` in `org-mode` by default. Now type `brain:` and press `TAB` for completion. This allows you to complete among all your `org-brain` entries. When you have chosen one the correct link will be created.

**Comment by xdrie** [comment]
when i try that, i get this: 
![image](https://user-images.githubusercontent.com/54390138/81617365-2a2c1480-939a-11ea-828e-cb6da0ebca06.png)

`symbol's value as variable is void: org-link--insert-history`

**Comment by Kungsgeten** [comment]
Hi! Sorry for the very late response. I think this issue was fixed in an earlier commit. It was due to `org-link--insert-history` being a new variable and in earlier versions of `org-mode` it was named `org-insert-link-history`.

**Comment by xdrie** [comment]
Thanks!
