### ISSUE TITLE
"Not a brain file" when brain files are symbolic links

### ISSUE THREAD

**Issue by ahmed-shariff** [Kungsgeten/org-brain#322]
The `org-brain-entry-at-pt` results with the error: `Not in a brain file` when the brain file I am looking at is a symlink. 

The problem seems to come from these lines: https://github.com/Kungsgeten/org-brain/blob/671db0e08b91c7d2637d765a7afca8b2561275c8/org-brain.el#L808-L809

In my case the `org-brain-path` is `~/Documents/brain` which expands to `/home/a/Documents/brain`. Here the `org` directory is a symlink to `/media/files/brain`. And `buffer-file-name` return the absolute path: `/media/files/brain/brain_file.org`

**Comment by ahmed-shariff** [comment]
A solution to this is: https://www.emacswiki.org/emacs/symlink-fix.el

**Comment by Kungsgeten** [comment]
Hi! Sorry for the late response. I'm not a heavy user of symbolic links myself, so I have some trouble wrapping my head around this. Do you have symbolic links inside of your `org-brain-path`, or do you have symbolic links linking to files in the `org-brain-path`? I don't quite understand the situation where the problem occurs. There's a variable named `buffer-file-truename` which follows symbolic links, maybe that could be used instead of `(buffer-file-name)` but I'm not sure.

**Comment by ahmed-shariff** [comment]
It's no problem, I totally understand :)

I use my brain files across different pc's and OS's. To make things easy for me I use symlinks to point to the brain files. In my case the symlink is `~/Documents/brain` which points to different "absolute" paths in different instances. Given how `buffer-file-name` works, when the `org-brain-path` and and the `buffer-file-name` don't have the same prefix, as one would be the symbolic link 
(`org-brain-path`) and the other returns the full-path (`buffer-file-name`). Does this make sense?

If my understanding of `buffer-file-truename` is correct, it returns the absolute path of the current buffer, right? The `buffer-file-name` also seems to return the absolute path. Which still doesn't solve the problem as `org-brain-path` doesn't point to the absolute path. Perhaps `file-truename` can help. I'll test it and submit a PR if it works.

**Comment by Kungsgeten** [comment]
Should be fixed now with @ahmed-shariff PR #335. Thanks!
