### ISSUE TITLE
README Improvement? RE: Persistent org-brain-headline-cache

### ISSUE THREAD

**Issue by HanshenWang** [Kungsgeten/org-brain#346]
Dear Mr. Kungsgeten, 

Thank you so so much for creating org brain. 

I'm currently running org brain in spacemacs, with maybe 9 MB of text and around 2500 headlines. Upon a fresh Emacs startup, the first run of org-brain-visualize takes around 30 to 40 seconds, with subsequent calls instantaneous. M-x profiler-report indicated org-get-tags to take up the most cpu cycles. I am not an experienced enough lisper to go beyond that, I'm afraid, and I think spacemacs running hooks everywhere may have something to do with it. 

Regardless, the package is an absolute blessing. What made it even more usable was making the org-brain-headline-cache persist across sessions. This completely eliminated the long initial startup. Experienced lispers probably have their own session management solutions (https://github.com/thierryvolpiatto/psession?), but for new folks like myself it was using Savehist.el -- included in emacs 22+ -- with just 2 lines of configuration:

```
;; If you're not using spacemacs,
(savehist-mode 1)
(setq savehist-additional-variables '(org-brain-headline-cache))
```

Maybe this information could be of use to more inexperienced people like myself as a little footnote in the "org-brain is slow!" section of the README.

As an aside: why is org-roam more popular, at least in terms of github stars, than org-brain? I believe that org-brain is just as capable of a zettelkasten-like workflow. Please correct me if I'm wrong but isn't aim of zettelkasten to give "form" to ideas organically? And in practice this means backlinks? 

I've tried both and as of now, org-roam is designed for you to use files as the most atomic unit instead of org-brain, which allows you to use both headlines and files. Two areas which org-roam excels over org-brain is the visualization (although there is org-brain-export and org-mind-map) and probably performance (as org roam uses a database). 

Still, both are wonderful projects. Org-brain just feels wider in scope. To be more in control of your information by allowing you to assign, in a top-down fashion, "form" to your ideas explicitly and more comprehensively, as well as bottom-up. The ability to have 2 parents for example, is lovely. 

Rambled on for long enough, it would be nice if org-brain were more popular (it and the Brain is ahead of its time). Maybe a video of the Brain (software) and org-brain side by side would serve as a good introduction. More users means maybe the project is maintained for longer, hopefully :)

Thanks again for taking the time to create org-brain!

**Comment by randomwangran** [comment]
> why is org-roam more popular, at least in terms of GitHub stars, than org-brain?

Stars are only part of the story. If a package works for you even with only a
few stars, it does not matter. I think the main reason why Org-roam is
popular is because of the introduction of the Zettelkasten method in 2020.

> I believe that org-brain is just as capable of the zettelkasten-like workflow.

Please correct me if I'm wrong but isn't the aim of Zettelkasten to give
"form" to ideas organically?

Org-brain was born early than the ideas of Zettelkasten got
popularity. I was attracted by Org-brain and tried to build a similar
thing like Zettelkasten before the Org-roam.

Although I still use Org-brain, I still use Org-brain frequently. I
relocated the structure notes from Org-roam. Now Org-roam is
preparing a huge change. In the new version, the headline will be the
foundation. And I believe there are many things we can do to bring
those two together.

**Comment by Kungsgeten** [comment]
Hi! Sorry for not responding to this. Does the `savehist` configuration still work, or is the reason that you closed the issue that something went wrong? I haven't tried it myself, but it seems like a nice solution that probably should be added to the README.

I think `org-roam` is popular because the author has written a lot of blog posts about it, created a community and also based it on Roam Research which got a lot of attention some time ago. Roam has a very clear method: "This is how you do things", which is nice and tailored toward the "Zettelkasten method". `org-brain` is similary inspired by a piece of software: The Brain. However The Brain is more open ended and it can be hard to figure out how to structure it all -- you have to make your own structure and workflow. That being said I think that `org-brain` works well for the Zettelkasten method, if that is how you want to use it.

The goal from the beginning in `org-brain` was to make it an extension of `org-mode` and Emacs, but this has changed somewhat over the years (now we're using special properties etc to increase performance). `org-roam` instead (if I understand it correctly) copies some functionality which could easily be done in other parts of Emacs, in order to make it a complete experience without configuration. It also uses external programs and a database, which `org-brain` doesn't do.

I've been thinking about writing an article of how `org-brain` can be used for a Zettelkasten workflow, but haven't taken the time to do it yet.

**Comment by HanshenWang** [comment]
Hey Kungsgeten and Randomwangran,

No worries at all! Thanks for taking the time to write that up! I did not know about the org-roam rewrite, and I'll most definitely give it a spin when its ready. Absolutely, bringing together the visualization capabilities and emacsql enabled speeds of org-roam with the flexibility of org brain (nicknames and annotations are just 2 examples of the little features in org-brain that I love) sounds like an ideal package. 

Lack of a database dependency can be a plus I guess. And I am beginning to use org-expiry to delete old unused entries. 

The savehist configuration still works. And with it being built in emacs, its nice and simple.

Should have noted this when I closed the issue, https://github.com/Kungsgeten/org-brain/pull/348 is my edit to the README. 

Cheers,
