### ISSUE TITLE
Possibility to wrap titles

### ISSUE THREAD

**Issue by minkkinen** [Kungsgeten/org-brain#52]
I have some very long entry titles that are formulated as questions. Would it be possible to wrap the boxes in the visualize buffer so that the box is a certain width and it can have several lines of text? Of course visual-line-mode works for the whole buffer, but that breaks the concept map layout.

Edit: Related Reddit discussion: https://www.reddit.com/r/emacs/comments/4rxj4j/how_to_create_large_multiline_buttons_in_a_buffer/

Multiline buttons may not be possible.

**Comment by Kungsgeten** [comment]
I do think multiline buttons are possible, the problem is that the second line should be indented, to the same level as the first. I do not think that is possible. An alternate solution might be to add a new variable, like `org-brain-max-title-length`, and titles would be capped if longer than this. So for instance `How to create large multiline buttons in a buffer` could become `How to create large mu...`, or something similar. Do you think that would suffice?

**Comment by Kungsgeten** [comment]
I haven't heard back from you, but I've added the variable `org-brain-title-max-length`, which hopefully solves your issue somewhat (even though it isn't perfect).
