### ISSUE TITLE
Show headers without an id in "Text" field

### ISSUE THREAD

**Issue by falematte** [Kungsgeten/org-brain#59]
Due to the fact that the system can become quite slow with an high nuber of nodes I usually do not give an ID to every header in an org file. Anyway It would be usefull to be able to see these headers in the "text" field of their parent (which has got an Id) in org brain visualize.

**Comment by Kungsgeten** [comment]
That would probably be useful, but I'm afraid it would slow down the fetching of text considerably (though perhaps not a problem in most cases). We would need to go through every child heading and see if it has an ID or not.

What you can do currently is to add a `childless` tag to the parent. This will show the subheadings in the text field. The downside is if you have mixed child headings, where some have IDs and some do not. `childless` will make it so that none of the child headings are considered as `org-brain` entries. Perhaps we could add another "special tag", like `showchildren` or similar, which shows the child headings in the text field, but still considers them as entries if they have an ID.

**Comment by falematte** [comment]
Thank you for your answer I believe this will be a great feature for this software.

**Comment by Kungsgeten** [comment]
I've now added a `showchildren` tag. It shows the entire subtree of an entry in the text field (only available for headline entries). My guess is that this is the most common user case, instead of wanting to show only subtrees without an ID. I'm closing this, but please feel free to open it again if you do not agree.

**Comment by dangom** [comment]
> "_My guess is that this is the most common user case_"

Is there a way to have `showchildren` always be the default, instead of having to add it manually?!
