### ISSUE TITLE
[question] Why the design decision to spread concepts across files?

### ISSUE THREAD

**Issue by danieroux** [Kungsgeten/org-brain#62]
I am quite excited about org-brain.

Why choose to spread a concept per file? I would want a concept per top-level headline, all in one file.

For three reasons:

- I really want to use sentences as concepts. Trying org-brain out, I got to "Quotes" and wanted to enter a quote. It broke, because the filename tried to have spaces and quote marks in it.
- I've been maintaining a brain.org.gpg (plain org-mode) file for the last 5 years, annotating the entries over time with parents/children/friends would be awesome.
- My brain.org.gpg file is encrypted, versioned and backed up as a single file and I trust that.

**Comment by Kungsgeten** [comment]
Hi! Have you watched my YouTube video on `org-brain`? If that is the case, many things has changed since then. It is now possible to have entries/concepts both as files and as headlines. I think that the use case you desire should be possible.

In your `org-brain-directory` you'd have a single file, let's call it `index.org`. Now you'll have an entry/concept called `index`, because the file itself is considered an entry. Now if you run `org-brain-visualize` on `index`, you can create top level headline entries (which will also become children of `index`, which perhaps is bad in your use case) by pressing `h` (creates a "local child", a headline under the current entry). If you're visualizing another entry, you can press `c` (for child) or `p` (for parent) or `f` (for friend) and type, for instance `index::Quotes` to create a new top level headline entry named `Quotes` in the index file. When visualizing `Quotes`, you could press `h` and type `"To be or not to be?"`, and that would be added as a sub-heading (and child) to `Quotes`, or you could press `c` and type `index::"To be or not to be?"` if you wanted it as a top level entry in the file, but still as a child to `Quotes`.

The reason why you'd perhaps want several files would be to organize concepts "better". Another reason might be that entry names currently are shown as `<file>::<headline>`, which can lead to clashes if you have the same headline name in several places in a file, but at different levels.

Not sure if this makes things clearer? If there's something you need to make `org-brain` more usable for your workflow, please let me know.

**Comment by Kungsgeten** [comment]
I'm marking this as closed, since it is possible to not spread concepts across files.
