### ISSUE TITLE
Bindining org-brain-visualize-back in ryo

### ISSUE THREAD

**Issue by rsuhada** [Kungsgeten/org-brain#64]
I rebind many keys org-brain in ryo (as you can see I'm a fan of your work :)). 
Everything works except `org-brain-visualize-back`. Here is an example what I do

    (ryo-modal-major-mode-keys
       'org-brain-visualize-mode
       ("e" org-brain-new-child)
       ("a" org-brain-visualize-back))

`org-brain-new-child` works but not `org-brain-visualize-back` (unknown function nil...)

Thank you!

**Comment by Kungsgeten** [comment]
I believe it is because `org-brain-visualize-back` isn't autoloaded. Emacs doesn't know about it until you run another `org-brain` related command. This isn't usually an issue, since you will have run `org-brain-visualize` before it makes sense to use `org-brain-visualize-back`. Try to add `(require 'org-brain)` before you add the ryo bindings, I think that'll work.

**Comment by rsuhada** [comment]
Thank you. You are right - adding the require into the `:init clause of `use-package` solves the issue.
