### ISSUE TITLE
Visualize entry at point

### ISSUE THREAD

**Issue by namdnguyen** [Kungsgeten/org-brain#65]
What do you think about having `org-brain-visualize` go to the entry at point, if it's an org-brain entry or file? If it's not an org-brain entry or file, then it can open up the menu to pick an entry to visualize. I often want to see who the parents and friends are for an entry that I am reading, so it would be nice to be able to jump to the visualization for it right from the entry. This behavior could be the default behavior or another configuration setting.

**Comment by Kungsgeten** [comment]
Hi! If I remember correctly it worked this way before version 0.4 (where I rewrote everything). I'm not really sure why I haven't implemented it again. Anyway I've now commited a change which sort of does what you describe. Instead of jumping directly to the entry at point, it will suggest the entry at point to the completion framework; if you want to jump elsewhere you just delete what's in the minibuffer.

Also a tip: If you want to jump to (or just check) a child/parent/friend when you're at an entry you can use `M-x org-brain-goto-parent` (or `child` or `friend`).

**Comment by namdnguyen** [comment]
Thanks! Also thank you for pointing me to the goto functions; very helpful!
