### ISSUE TITLE
org-mode headlines break org-brain "Entry" display

### ISSUE THREAD

**Issue by naclander** [Kungsgeten/org-brain#95]
If an org-brain org file contains the following

```
foo foo foo 
* This is an Org headline
This doesn't show =(
```
Then the org heading, and anything below it ( `This doesn't show =(` ) will not be shown in the Entry section when visualizing the brain.

I do not think this is intended, and I didn't see any documentation mentionig this. Is this a bug?

**Comment by Kungsgeten** [comment]
When getting the entry text for a file, the text before the first headline is fetched by default. This is because headlines are usually entries of their own. I _think_ you can tag the headline with `:nobrain:` in order to show it inside the file entry text.

**Comment by naclander** [comment]
The README says the `:nobrain:` tag does:
> This tag excludes the headline, and its subheadings, from your org-brain entries

I just want the Entry to show the whole file, but wouldn't this tag remove it from my brain? I don't think that's what I want.

In a way I think what org-brain is doing is trying to only show in the "Entry" section the "summary" of the document? i.e. anything before the first headline? I think that makes sense, but I would add it to the readme. 

But on the other hand, it is a little frusterating if I try to add more complex org documents to my brain. If my org document contains many headings, or a heading right at the beginnign, I potentially might miss out some resources ( links ) and in the worst case I'll just see nothing which is a little confusing. 

Making this feature be turned on/off by the user would be my preferred solution.

**Comment by Kungsgeten** [comment]
It is now possible to set tags on file entries (using `org-brain-set-tags`, bound to `T` in `org-brain-visualize). If you have a file entry and want to see all the headings, you can add the `:showchildren:` tag or `:childless:` tag, depending on if you want the treated as entries or not.

**Comment by naclander** [comment]
@Kungsgeten I'm a little confused how the :showchildren: and :childless: tag is related to showing the full org file in the entries, can you elaborate on that please? I thought children refer to a completely different thing in org brain

Why is the default behavior not to show the entire org file in the entry?

I see your commit added some minor details in the README, but I think further clarification is still needed.

**Comment by EFLS** [comment]
Only things that have an `org-id` are shown in `org-brain`.

So make sure that the headings you want `brain` to see have an ID. Create one with `M-x` `org-id-get-create` or `org-id-copy`.

As far as I understand, the tags are only relevant to change the behaviour *when an ID is already present*.

**Comment by azzamsa** [comment]
> Why is the default behavior not to show the entire org file in the entry?

Have the same question. Hope Mr. Sjöstrand will come to explain.

**Comment by Kungsgeten** [comment]
The default is to only show the text of the visualized entry. If your entry is a file, the shown text will be (by default) the text before the first heading in the file. This is because in org-brain, usually, headlines are entries of their own. If you want to show the text of the local children (subheadings) when visualizing an entry, you can add the `:showchildren:` tag. If you want the file/headline and its children (subheadings) to be treated as a single entry, you can add the `:childless:` tag instead.

What makes most sense probably has to do with if you primarily use files to organize entries, or if you use headlines. Let's say I have a file called `programming.org`, which have subheadings (children) for Python, C, Lisp, JavaScript, Erlang etc. This could be a pretty large file, and I probably don't want to see all the text in the file when visualizing the `Programming` entry. If you instead were to put all these languages in separate files, it would probably make more sense to add `:showchildren:` to them. It is all about the workflow and what makes most sense for you :)

**Comment by azzamsa** [comment]
> This is because in org-brain, usually, headlines are entries of their own

> This could be a pretty large file, and I probably don't want to see all the text in the file when visualizing the Programming entry. 

Agree. It's also make visualizing the brain become more cleaner.

Actually. I like this default even before you come to explain :). Because I can put short text before first heading. And jump to that file if I need to see the whole content. without messing the visualization buffer.

Thank you so much for this package. I hope we can export it to any file. So it can be shared to others.

Thank you for your contribution to community.

**Comment by naclander** [comment]
@Kungsgeten  I've been thinking about this more, and while I agree that a potentially large org file with many  headlines would be annoying/difficult/ugly to show in `org-brain-visualize`, I think there are many users who set want to set up their org-brain files in a variety of different ways. 

Not to mention users who want to take their existing files and convert them to org-brain files.

Would it be a fair compromise to make this configurable? I.e., the default behavior can be to not show headlines, but have a an org-brain variable that that displays everything? Thoughts?

**Comment by naclander** [comment]
@Kungsgeten  What I really want is a mechanism in which regardless of the org file format, I see everything in the file in the `entry` section. 

As I was playing around with org-brain, I got into this situation:

Snippet from an entry file:

```
:RESOURCES:
:END:
#+BRAIN_PARENTS: grandparent-entry

#+TITLE: test-entry-new-title
#+FILETAGS: Test:Tag:More-tags
#+BRAIN_CHILDREN: test-child test-child-3 test-child-4

- [[https://example.com][This is a resource]]
  
words

more words

Here is an important list:
* item 1
* item 2
* item 3

  
More important words

- [[https://example.com][This is another important resource]]
```

And this is how the file is displayed in org-brain visualize:

```
--- Resources ---------------------------------

• This is a resource

--- Entry -------------------------------------

- [[https://example.com][This is a resource]]
  
words

more words

Here is an important list:
```

To me, as a first time user of org-brain, this seems broken. And is not what I want. 

So it would be nice to have some variable ( totally fine if not enabled by default ), that would show me this instead:
```
--- Resources ---------------------------------

• - [[https://example.com][This is a resource]]
* - [[https://example.com][This is another important resource]]

--- Entry -------------------------------------

- [[https://example.com][This is a resource]]
  
words

more words

Here is an important list:
* item 1
* item 2
* item 3

- [[https://example.com][This is another important resource]]
```
Does this make sense?
