### ISSUE TITLE
org-brain-text-hook

### ISSUE THREAD

**Issue by d12frosted** [Kungsgeten/org-brain#99]
Hey,

I see that there is a hook called `org-brain-after-visualize-hook` which is run **before** `org-brain-text` function. This is great but would be even better to have a hook after that named function. 

Simple use case: preview all latex (using `org-toggle-latex-fragment`) 😃

WDYT?

**Comment by Kungsgeten** [comment]
Perhaps you can do that with `defadvice`, instead of a hook? The reason for the hook being run before the text is mainly if you want to convert the buffer to ascii-art, in which case the entry text should probably be excluded.

You could perhaps do:

```
(defadvice org-brain-visualize (after latex-fragments activate)
  (org-toggle-latex-fragment t))
```

Not sure if the above would work right out of the box, but something similar to that.

**Comment by d12frosted** [comment]
Hey, thanks for quick response!

Actually, I was talking about creating a new hook 😸 I understand the purpose of the `org-brain-after-visualize-hook`. Just wanted to say that there are cases when you want to do something *after* the text is inserted.

But yeah, advice works well. I don't consider myself a fan of advices, though 😹

**Comment by Kungsgeten** [comment]
Aah, now I see :) Sure, I can add a new hook. I can see two variants:

1. The hook is run after the text is inserted into `org-brain-visualize`. This means that the functions in the hook act on the entire buffer.
2. The hook is run when fetching the text from `org-mode`. This means that only the entry text would be affected, and not the other parts of the visualize interface.

To me variant two seems better, and it'll also be different from simply advicing `org-brain-visualize`. What do you think?

**Comment by Kungsgeten** [comment]
I tried creating the hook `org-brain-visualize-text-hook` as suggested in "option 2" above. The problem is that overlays (like the ones created by `org-toggle-latex-fragments`) aren't copied between buffers. Because of this I'm using "option 1" instead, which seems to work.

An alternative might be to narrow the `org-brain-visualize` buffer to the entry text, before running the hook, but at the moment that isn't the case.

**Comment by d12frosted** [comment]
@Kungsgeten thanks a lot for implementing this :)
